<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>EyeOfProvidence</AssemblyName>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>EyeOfProvidence</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.29" IncludeAssets="compile" />

    <Reference Include="PluginConfigurator">
      <HintPath>lib/EternalsTeam-PluginConfigurator-1.10.2/PluginConfigurator.dll</HintPath>
    </Reference>
    <Reference Include="PluginConfiguratorComponents">
      <HintPath>lib/EternalsTeam-PluginConfigurator-1.10.2/PluginConfiguratorComponents.dll</HintPath>
    </Reference>

    <Reference Include="Assembly-CSharp-publicized">
      <HintPath>lib/17d4/Assembly-CSharp-publicized.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>lib/17d4/UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>lib/17d4/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>lib/17d4/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>lib/17d4/Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Timeline">
      <HintPath>lib/17d4/Unity.Timeline.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>